### ISSUE TITLE
Pypi release new version

### ISSUE THREAD

**Issue by uSpike** [facebook/fbtftp#24]
Hello, great project!

Would you please consider releasing a "0.2" version to pypi?  There's been a number of fixes since the 0.1 release last year and it'd be a great help for us to be able to install from pypi directly.

Thanks!

**Comment by pallotron** [comment]
yes, will do.

**Comment by pallotron** [comment]
https://pypi.python.org/pypi?:action=display&name=fbtftp&version=0.2
