### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by stasfilin** [facebook/fbtftp#26]
Problem with MacOS.
OS: 64bit Mac OS X 10.12.6 16G29
```python
self._epoll = select.epoll()
AttributeError: module 'select' has no attribute 'epoll'
```

Module select doesn't have epoll method. I want to try to fix this with another way. 

It's critical or not?

Thanks

**Comment by pallotron** [comment]
yeah, we know about this, MacOSX doesn't have support for epoll. they have a different API for similar things. To be quite frank with you I am not expecting people to run tftp servers on MacOSX in production :)
TFTP is usually used on datacenter/ISP environment.
Adding support for MacOSX is not in our imminent roadmap, but we accept PRs if you are bored :)

**Comment by pallotron** [comment]
I believe that `kqueue()` on BSD/MacOS is the equivalent of `epoll()` for Linux

**Comment by pallotron** [comment]
I don't think fbtftp is meant to run on OSX, it's meant to run on Linux servers. We don't need to run this on OSX in our FB infra. I am closing this task. We obviously accept PRs from anyone that needs this and is willing to make the code change to use whatever polling mechanism OSX supports.
