### ISSUE TITLE
How to reject client request with ERR_FILE_NOT_FOUND?

### ISSUE THREAD

**Issue by juliacartwright** [facebook/fbtftp#29]
Hello, first off thanks for the great project!

I'm having trouble figuring out what the best way to respond to a client w/ ERR_FILE_NOT_FIND (error 1) .   Would this be done as part of the server's get_handler()?  Of the handler's get_response_data()?  The handler has a private method _transmit_error() which would seem to be useful, but it appears to only be intended to be called by fbtftp internals?

Any pointers will be helpful.  Thanks!

**Comment by pallotron** [comment]
Hey sorry for the late response, I was off for the holidays. :-)

So you could use `get_response_data` and throw an exception there if the file is not found or you have any error. Exception will be caught and a `ERR_UNDEFINED` error will be returned to the client as you see here:

https://github.com/facebook/fbtftp/blob/master/fbtftp/base_handler.py#L145

That is supposing that returning `ERR_UNDEFINED` is ok for you.

**Comment by pallotron** [comment]
One better way could be to define a new `GetResponseDataException` that carries a message string together with a TFTP error code constant as defined in https://github.com/facebook/fbtftp/blob/master/fbtftp/constants.py#L21

**Comment by pallotron** [comment]
if you decide to go with the latter proposal we are more than happy to review your PR!!! :)

**Comment by pallotron** [comment]
I am closing this "issue". Please feel free to reopen if you need more clarifications and as I already said feel free to send us a PR if you want to implement the last thing I suggested :)
