### ISSUE TITLE
SyntaxError when running the example in readme

### ISSUE THREAD

**Issue by cbowesntu** [facebook/fbtftp#40]
Hi,
I'm running into an issue when trying to run the example server that is displayed in the repo's readme.

I have made no changes to the code so is word for word from the repo.

OS: CentOS 7

[root@webnettftp fbtftp]# python3 webnetTFTP.py
  File "webnetTFTP.py", line 51
    root='/var/tftproot', print_session_stats,
SyntaxError: positional argument follows keyword argument

Thanks,
Cameron

**Comment by pallotron** [comment]
well yeah the problem is that you cannot have a positional argument after the keyword ones:

```
server = StaticServer(ip='', port='1069', retries=3, timeout=5,
                          root='/var/tftproot', handler_stats_callback=print_session_stats,
                          server_stats_callback=print_server_stats)
```
send a PR if you want to fix the example otherwise I will fix it later.

**Comment by cbowesntu** [comment]
Ok cheers, done a pull request
