### ISSUE TITLE
FreeBSD compatibility

### ISSUE THREAD

**Issue by lamaral** [facebook/fbtftp#48]
Hi guys,

Would it be on your interest to have BSD compatibility added to the framework? 

If it's of interest to you, I will work on making it compatible with both BSD and Linux and send a PR. 
I already have it BSD-only in my fork, so I figured it wouldn't be too much work to get both.

**Comment by lamaral** [comment]
Ah, I see on #26 that a PR is welcome :)
I'll see if I can get back with a PR still this week.

**Comment by skozlov404** [comment]
Connecting the PR: #49
