### ISSUE TITLE
Consider removing Python 2 compatibility code

### ISSUE THREAD

**Issue by berkerpeksag** [facebook/fbtftp#5]
Hello,

README says:

> fbtftp is written in python3 [...]

and lists Python 3.x as a requirement at https://github.com/facebook/fbtftp#requirements. setup.py also defines it as a Python 3 only project: https://github.com/facebook/fbtftp/blob/master/setup.py#L41

However, the code base has some code for Python 2 compatibility (`__future__` imports, `codecs.open`, `class Spam(object):` etc.) and follows some old practices like https://github.com/facebook/fbtftp/blob/master/examples/server.py#L68.

Is there any Python 2 deployment out there (probably not since it will require the backport of ipaddress module) or can they be safely removed now? I can send a pull request if they are not needed now.

Thanks!

**Comment by pallotron** [comment]
They can be safely removed, we exclusively run on Python 3.
I will work on this next week, thanks for reporting this!

**Comment by pallotron** [comment]
that said, this is OS project so PR are welcome :)
